# For full config options, check the docs:
#    docs.serverless.com
#
service: corona-api
org: ndom91
app: corona-api

plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'eu-central-1'}

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
      Resource: "arn:aws:dynamodb:eu-central-1:392655045323:table/corona1/*"
    - Effect: "Allow"
      Action:
        - "s3:PutObject"
      Resource: "arn:aws:s3:::corona-api-json-content"
    - Effect: "Allow"
      Action:
        - "secretsmanager:GetSecretValue"
      Resource: "arn:aws:secretsmanager:eu-central-1:392655045323:secret:envs"

  environment:
    REDIS_PASS: ${self:custom.ssm.REDIS_PASS}
    REDIS_PORT: ${self:custom.ssm.REDIS_PORT}
    REDIS_URL: ${self:custom.ssm.REDIS_URL}
    BUCKET_NAME: "corona-api-json-content"
    DDBtable: "corona1"
    SLS_DEBUG: "*"

  tracing:
    apiGateway: true
    lambda: true

custom:
  ssm: ${ssm:/aws/reference/secretsmanager/envs~true}
  webpackIncludeModules: true
  webpack:
    includeModules: true
    packager: "npm"
    webpackConfig: "webpack.config.js"

package:
  include:
    - package.json
    - functions/**
    - node_modules/**

functions:
  dailyCases:
    handler: functions/daily.handler
    events:
      - http:
          path: daily
          method: get
  meta:
    handler: functions/meta.handler
    events:
      - http:
          path: meta
          method: get
  datasources:
    handler: functions/datasources.handler
    events:
      - http:
          path: datasources
          method: get
  flushredis:
    handler: functions/flushredis.handler
    events:
      - http:
          path: flushredis
          method: get
  getData:
    handler: functions/getData.handler
    events:
      - schedule: cron(01 0 * * ? *)
      - http:
          path: getData
          method: get
  total:
    handler: functions/total.handler
    events:
      - http:
          path: total
          method: get
  graphql:
    handler: functions/graphql/handler.graphqlHandler
    events:
      - http:
          path: graphql
          method: post
      - http:
          path: graphql
          method: get
