# For full config options, check the docs:
#    docs.serverless.com
#
service: corona-api
org: ndom91
app: corona-api

provider:
  name: aws
  runtime: nodejs12.x

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
      Resource: "arn:aws:dynamodb:eu-central-1:392655045323:table/serverlessrepo-s3-to-dynamodb-importer-json-DDBtable-QF81U10PRNS6"
    - Effect: "Allow"
      Action:
        - "s3:PutObject"
      Resource: "arn:aws:s3:::corona-api-json-content"

  stage: dev
  region: eu-central-1

  environment:
    REDIS_PASS: ${ssm:/REDIS_PASS~true}
    REDIS_PORT: ${ssm:/REDIS_PORT~true}
    REDIS_URL: ${ssm:/REDIS_URL~true}
    BUCKET_NAME: "corona-api-json-content"
    DDBtable: "corona1"
    DDBtable2: "serverlessrepo-s3-to-dynamodb-importer-json-DDBtable-QF81U10PRNS6"

package:
  include:
    - package.json
    - functions/**
    - node_modules/**

functions:
  dailyCases:
    handler: functions/daily.handler
    events:
      - http:
          path: daily
          method: get
  meta:
    handler: functions/meta.handler
    events:
      - http:
          path: meta
          method: get
  flushredis:
    handler: functions/flushredis.handler
    events:
      - http:
          path: flushredis
          method: get
  getData:
    handler: functions/getData.handler
    events:
      - schedule: cron(01 0 * * ? *)
      - http:
          path: getData
          method: get
