# For full config options, check the docs:
#    docs.serverless.com
#
service: corona-api
org: ndom91
app: corona-api

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'eu-central-1'}

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
      Resource: "arn:aws:dynamodb:eu-central-1:392655045323:table/corona1"
    - Effect: "Allow"
      Action:
        - "s3:PutObject"
      Resource: "arn:aws:s3:::corona-api-json-content"
    - Effect: "Allow"
      Action:
        - "secretsmanager:GetSecretValue"
      Resource: "<SECRET MANAGER ARN>"

  environment:
    REDIS_PASS: ${self:custom.secrets.REDIS_PASS}
    REDIS_PORT: ${self:custom.secrets.REDIS_PORT}
    REDIS_URL: ${self:custom.secrets.REDIS_URL}
    BUCKET_NAME: "corona-api-json-content"
    DDBtable: "corona1"

  tracing:
    apiGateway: true
    lambda: true

custom:
  secrets: ${ssm:/aws/reference/secretsmanager/dev/coronaapi~true}

package:
  include:
    - package.json
    - functions/**
    - node_modules/**

functions:
  dailyCases:
    handler: functions/daily.handler
    events:
      - http:
          path: daily
          method: get
  meta:
    handler: functions/meta.handler
    events:
      - http:
          path: meta
          method: get
  flushredis:
    handler: functions/flushredis.handler
    events:
      - http:
          path: flushredis
          method: get
  getData:
    handler: functions/getData.handler
    events:
      - schedule: cron(01 0 * * ? *)
      - http:
          path: getData
          method: get
  total:
    handler: functions/total.handler
    events:
      - http:
          path: total
          method: get
